Update to latest version of Nimble and Quick
This commit addresses issue #22, by updating to the latest versions of the Nimble and Quick libraries, which compile successfully under Xcode 7.3.

diff --git a/Example/Carthage/Checkouts/Nimble/script/release b/Example/Carthage/Checkouts/Nimble/script/release
--- a/Example/Carthage/Checkouts/Nimble/script/release
+++ b/Example/Carthage/Checkouts/Nimble/script/release
@@ -1,5 +1,5 @@
 #!/usr/bin/env sh
-REMOTE_BRANCH=swift-2.0
+REMOTE_BRANCH=master
 POD_NAME=Nimble
 PODSPEC=Nimble.podspec
 GITHUB_TAGS_URL=https://github.com/Quick/Nimble/tags
@@ -13,6 +13,7 @@ function help {
     echo
     echo "VERSION should be the version to release, should not include the 'v' prefix"
     echo "RELEASE_NOTES should be a file that lists all the release notes for this version"
+    echo "              if file does not exist, creates a git-style commit with a diff as a comment"
     echo
     echo "FLAGS"
     echo "  -f  Forces override of tag"
@@ -52,8 +53,20 @@ if [ -z "`which $POD`" ]; then
 fi
 echo " > Cocoapods is installed"
 
+echo " > Is this a reasonable tag?"
+
+echo $VERSION_TAG | grep -q "^vv"
+if [ $? -eq 0 ]; then
+    die "This tag ($VERSION) is an incorrect format. You should remove the 'v' prefix."
+fi
+
+echo $VERSION_TAG | grep -q -E "^v\d+\.\d+\.\d+(-\w+(\.\d)?)?\$"
+if [ $? -ne 0 ]; then
+    die "This tag ($VERSION) is an incorrect format. It should be in 'v{MAJOR}.{MINOR}.{PATCH}(-{PRERELEASE_NAME}.{PRERELEASE_VERSION})' form."
+fi
+
 echo " > Is this version ($VERSION) unique?"
-git describe --exact-match "$VERSION_TAG" 2>&1 > /dev/null
+git describe --exact-match "$VERSION_TAG" > /dev/null 2>&1
 if [ $? -eq 0 ]; then
     if [ -z "$FORCE_TAG" ]; then
         die "This tag ($VERSION) already exists. Aborting. Append '-f' to override"
@@ -65,7 +78,23 @@ else
 fi
 
 if [ ! -f "$RELEASE_NOTES" ]; then
-    die "Failed to find $RELEASE_NOTES. Aborting."
+    echo " > Failed to find $RELEASE_NOTES. Prompting editor"
+    RELEASE_NOTES=.release-changes
+    LATEST_TAG=`git for-each-ref refs/tags --sort=-refname --format="%(refname:short)" | grep -E "^v\d+\.\d+\.\d+(-\w+(\.\d)?)?\$" | ruby -e 'puts STDIN.read.split("\n").sort { |a,b| Gem::Version.new(a.gsub(/^v/, "")) <=> Gem::Version.new(b.gsub(/^v/, "")) }.last'`
+    echo " > Latest tag ${LATEST_TAG}"
+    echo "${POD_NAME} v$VERSION" > $RELEASE_NOTES
+    echo "================" >> $RELEASE_NOTES
+    echo >> $RELEASE_NOTES
+    echo "# Changelog from ${LATEST_TAG}..HEAD" >> $RELEASE_NOTES
+    git log ${LATEST_TAG}..HEAD | sed -e 's/^/# /' >> $RELEASE_NOTES
+    $EDITOR $RELEASE_NOTES
+    diff -q $RELEASE_NOTES ${RELEASE_NOTES}.backup > /dev/null 2>&1
+    STATUS=$?
+    rm ${RELEASE_NOTES}.backup
+    if [ $STATUS -eq 0 ]; then
+        rm $RELEASE_NOTES
+        die "No changes in release notes file. Aborting."
+    fi
 fi
 echo " > Release notes: $RELEASE_NOTES"
 
@@ -102,8 +131,8 @@ echo " > Verified ownership to $POD_NAME pod"
 echo "--- Releasing version $VERSION (tag: $VERSION_TAG)..."
 
 function restore_podspec {
-    if [ -f 'Nimble.podspec.backup' ]; then
-        mv -f Nimble.podspec{.backup,}
+    if [ -f "${PODSPEC}.backup" ]; then
+        mv -f ${PODSPEC}{.backup,}
     fi
 }
 
@@ -111,12 +140,14 @@ echo "-> Ensuring no differences to origin/$REMOTE_BRANCH"
 git fetch origin || die "Failed to fetch origin"
 git diff --quiet HEAD "origin/$REMOTE_BRANCH" || die "HEAD is not aligned to origin/$REMOTE_BRANCH. Cannot update version safely"
 
-echo "-> Building Carthage release"
-$CARTHAGE build --no-skip-current || die "Failed to build framework for carthage"
+# Don't build binaries: see https://github.com/Carthage/Carthage/issues/924
+# echo "-> Building Carthage release"
+# $CARTHAGE build --no-skip-current || die "Failed to build framework for carthage"
 
 echo "-> Setting podspec version"
 cat "$PODSPEC" | grep 's.version' | grep -q "\"$VERSION\""
-if [ $? -eq 0 ]; then
+SET_PODSPEC_VERSION=$?
+if [ $SET_PODSPEC_VERSION -eq 0 ]; then
     echo " > Podspec already set to $VERSION. Skipping."
 else
     sed -i.backup "s/s.version *= *\".*\"/s.version      = \"$VERSION\"/g" "$PODSPEC" || {
@@ -124,10 +155,8 @@ else
         die "Failed to update version in podspec"
     }
 
-    git add Nimble.podspec || { restore_podspec; die "Failed to add Nimble.podspec to INDEX"; }
+    git add ${PODSPEC} || { restore_podspec; die "Failed to add ${PODSPEC} to INDEX"; }
     git commit -m "Bumping version to $VERSION" || { restore_podspec; die "Failed to push updated version: $VERSION"; }
-    git push origin "$REMOTE_BRANCH" || die "Failed to push to origin"
-    echo " > Pushed version to origin"
 fi
 
 if [ -z "$FORCE_TAG" ]; then
@@ -142,12 +171,18 @@ else
     git push origin "$VERSION_TAG" -f || die "Failed to push tag '$VERSION_TAG' to origin"
 fi
 
+if [ $SET_PODSPEC_VERSION -ne 0 ]; then
+    rm $RELEASE_NOTES
+    git push origin "$REMOTE_BRANCH" || die "Failed to push to origin"
+    echo " > Pushed version to origin"
+fi
+
 echo
 echo "---------------- Released as $VERSION_TAG ----------------"
 echo 
-echo "Archiving carthage release..."
-
-$CARTHAGE archive "$CARTHAGE_FRAMEWORK_NAME" || die "Failed to archive framework for carthage"
+# Don't build binaries: see https://github.com/Carthage/Carthage/issues/924
+# echo "Archiving carthage release..."
+# $CARTHAGE archive "$CARTHAGE_FRAMEWORK_NAME" || die "Failed to archive framework for carthage"
 
 echo
 echo "Pushing to pod trunk..."
@@ -159,6 +194,7 @@ echo "================ Finalizing the Release ================"
 echo
 echo " - Go to $GITHUB_TAGS_URL and mark this as a release."
 echo "   - Paste the contents of $RELEASE_NOTES into the release notes. Tweak for Github styling."
-echo "   - Attach ${CARTHAGE_FRAMEWORK_NAME}.framework.zip to it."
+# echo "   - Attach ${CARTHAGE_FRAMEWORK_NAME}.framework.zip to it."
 echo " - Announce!"
 
+rm ${PODSPEC}.backup
